---
title: "Appendix A"
author: "Joshua Ingram"
date: "5/21/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(latex2exp)
library(wesanderson)

load(file = "D:/main/Projects/Solar-Flare-Project/power_sim_results_max.Rdata")
```

```{r}
# formatting results to be in dataframe format... removing 500 through 10000 sample size results
n <- c(10, 15, 20, 25, 30, 35, 40, 50, 60, 70, 80, 90, 100, 125, 150, 175, 200)

# results for exponential distribution fit
exp_power <- 1-t(as.data.frame(exp_fit_power))
rownames(exp_power) <- NULL
exp_power <- as.data.frame(cbind(n, exp_power))

# results for weibull distribution fit
weibull_power <- 1- t(as.data.frame(weibull_fit_power))
rownames(weibull_power) <- NULL
weibull_power <- as.data.frame(cbind(n, weibull_power))

# results for lognormal distribution fit
lognormal_power <- 1-t(as.data.frame(lognormal_fit_power))
rownames(lognormal_power) <- NULL
lognormal_power <- as.data.frame(cbind(n, lognormal_power))

# results for gamma distribution fit
gamma_power <- 1-t(as.data.frame(gamma_fit_power))
rownames(gamma_power) <- NULL
gamma_power <- as.data.frame(cbind(n, gamma_power))
```

```{r}
exp_power <- exp_power %>%
  select(n, ks, ks_lf, ad_lf, ad, ad_br) %>%
  gather(key = "test", value = "power", -n)

weibull_power <- weibull_power %>%
  select(n, ks, ks_lf, ad_lf, ad, ad_br) %>%
  gather(key = "test", value = "power", -n)

lognormal_power <- lognormal_power %>%
  select(n, ks, ks_lf, ad_lf, ad, ad_br) %>%
  gather(key = "test", value = "power", -n)

gamma_power <- gamma_power %>%
  select(n, ks, ks_lf, ad_lf, ad, ad_br) %>%
  gather(key = "test", value = "power", -n)
```

# Results

```{r}
ggplot(data = exp_power, aes(x=n, y=power)) +
  geom_hline(yintercept=0.05, linetype='dotted', col = 'red')+
  geom_line(aes(color = test)) +
  theme_bw() +
  labs(title = "Type-I Error Rate of GoF Tests", x = "Sample Size, n", y = "Type-I Error Rate", legend = "Test", subtitle = TeX("Sample drawn from $Exponential(\\lambda = 0.5)$"), color = "Test") +
  scale_color_brewer(label = c("A-D", "Braun-Adjusted", "Corrected A-D", "K-S", "Lilliefors"), palette = "Set2")
```

```{r}
ggplot(data = weibull_power, aes(x=n, y=power)) +
  geom_hline(yintercept=1, linetype='dotted', col = 'red')+
  geom_line(aes(color = test)) +
  theme_bw() +
  labs(title = "Power of GoF Tests", x = "Sample Size, n", y = "Power (% Reject Null)", legend = "Test", subtitle = TeX("Sample drawn from $Weibull(k = 1.4, \\; \\lambda = 2.5)$")) +
  scale_color_brewer(label = c("A-D", "Braun-Adjusted", "Corrected A-D", "K-S", "Lilliefors"), palette = "Set2")


```

```{r}
ggplot(data = gamma_power, aes(x=n, y=power)) +
  geom_hline(yintercept=1, linetype='dotted', col = 'red')+
  geom_line(aes(color = test)) +
  theme_bw() +
  labs(title = "Power of GoF Tests", x = "Sample Size, n", y = "Power (% Reject Null)", legend = "Test",  subtitle = TeX("Sample drawn from $Gamma(a = 2, \\; s = 0.5)$"))+
  scale_color_brewer(label = c("A-D", "Braun-Adjusted", "Corrected A-D", "K-S", "Lilliefors"), palette = "Set2")


```

```{r}
ggplot(data = lognormal_power, aes(x=n, y=power)) +
  geom_hline(yintercept=1, linetype='dotted', col = 'red')+
  geom_line(aes(color = test)) +
  theme_bw() +
  labs(title = "Power of GoF Tests", x = "Sample Size, n", y = "Power (% Reject Null)", legend = "Test", subtitle = TeX("Sample drawn from $LogNormal(\\mu = 0.1, \\; \\sigma^2 = 0.6)$"))+
  scale_color_brewer(label = c("A-D", "Braun-Adjusted", "Corrected A-D", "K-S", "Lilliefors"), palette = "Set2")
```

