---
title: "Chapter 2 - Solar Flare Observations"
author: "Joshua Ingram"
date: "5/11/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(latex2exp)
library(wesanderson)

GOES <- read_csv("D:/main/Datasets/Solar_REU/GOES_data/goes_clean.csv")
GOES$cycle <- as.factor(GOES$cycle)
GOES <- GOES %>% filter(is.na(Gflrtotalenergy) == FALSE | Gflrtotalenergy > 0)
GOES$goessat <- factor(as.factor(GOES$goessat), levels = c("GO7", "GO8", "GO9", "G10", "G11", "G12", "G13", "G14", "G15", "G16"))
```

# 2.1 GOES Satellites

```{r}
satellite_data <- GOES %>% select(goessat, Gpeak)
ggplot(data = satellite_data, aes(x = Gpeak, y = goessat, color = goessat)) + 
  geom_point() +
  theme_bw() +
  labs(title = "Active GOES Satellites in Detecting Flares", x = "Year", y = "Active Satellite", color = "GOES Series")
```

# 2.5

```{r}
ggplot(data = GOES, aes(x = log(Gflrtotalenergy, 10))) + 
  geom_histogram(bins = 1000, fill = "sienna2") + 
  theme_bw() + 
  labs(title = "Discretization of Flare Measurements Caused by Rounding", subtitle = "Number of bins set too 1,000",y = "Count", x = TeX("$\\log_{10}$(Total Energy)"))

```

