---
title: "Chapter 6 - Results and Discussion"
author: "Joshua Ingram"
date: "5/12/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(pracma)
library(tidyverse)
library(plotly)
source("D:/main/Projects/Solar-Flare-Project/Thesis Results/Code/mu_likelihood_functionsV2.R")

GOES <- read_csv("D:/main/Datasets/Solar_REU/GOES_data/goes_clean.csv")
GOES$cycle <- as.factor(GOES$cycle)
```

# Sigmoid Model

## Total Energy

```{r}
df <- ggplot(data = GOES, aes(x= log(Gflrtotalenergy, 10))) + geom_histogram(bins = 50)
bins_data <- ggplot_build(df)$data[[1]]
bins_data <- data.frame(y = bins_data$count, lb = bins_data$xmin, ub = bins_data$xmax, mids = bins_data$x)

theta0 = c(1.8, 60, 3, 27.5)

optim(par = theta0, fn = ll_test, df = bins_data, H0 = 24, 
      lower = c(1.001, 20, 0.1, 0.1))
```

```{r}
df <- ggplot(data = GOES, aes(x= log(Gflrtotalenergy, 10))) + geom_histogram(bins = 50)
bins_data <- ggplot_build(df)$data[[1]]
bins_data <- data.frame(y = bins_data$count, lb = bins_data$xmin, ub = bins_data$xmax, mids = bins_data$x)

theta0 = c(1.8, 23, 2, 1, 26)

optim(par = theta0, fn = ll_test2, df = bins_data, H0 = 24, 
      lower = c(1.001, 20, 0.1, 0.1, 24.5))
```

fit to ARs where exponential is a reasonable fit

# ED50 Model

## Total Energy

aggregate
```{r}
df <- ggplot(data = GOES, aes(x= log(Gflrtotalenergy))) + geom_histogram(center = 59, binwidth = 0.2)
bins_data <- ggplot_build(df)$data[[1]]
bins_data <- data.frame(y = bins_data$count, lb = bins_data$xmin, ub = bins_data$xmax, mids = bins_data$x)

theta_0 = c(60,1,350,68, 1)

results <- optim(par = theta_0, fn = ll, df = bins_data, 
      lower = c(55, .5, 50, 60, 0.8), method = "L-BFGS-B", hessian = TRUE)
```

by cycle
```{r}
theta_0 = c(60,1,350,65, 1)

results <- optim(par = theta_0, fn = ll, df = bins_data, 
      lower = c(55, .5, 100, 60, 0.8), method = "L-BFGS-B", hessian = TRUE)
```

by year
```{r}
theta_0 = c(60,1,350,65, 1)

results <- optim(par = theta_0, fn = ll, df = bins_data, 
      lower = c(55, .5, 100, 60, 0.8), method = "L-BFGS-B", hessian = TRUE)
```

active regions
```{r}
theta_0 = c(60,1,350,65, 1)

results <- optim(par = theta_0, fn = ll, df = bins_data, 
      lower = c(55, .5, 100, 60, 0.8), method = "L-BFGS-B", hessian = TRUE)
```

## Peak Flux

aggregate
```{r}
theta_0 = c(60,1,350,65, 1)

results <- optim(par = theta_0, fn = ll, df = bins_data, 
      lower = c(55, .5, 100, 60, 0.8), method = "L-BFGS-B", hessian = TRUE)
```

by cycle
```{r}
theta_0 = c(60,1,350,65, 1)

results <- optim(par = theta_0, fn = ll, df = bins_data, 
      lower = c(55, .5, 100, 60, 0.8), method = "L-BFGS-B", hessian = TRUE)
```

by year
```{r}
theta_0 = c(60,1,350,65, 1)

results <- optim(par = theta_0, fn = ll, df = bins_data, 
      lower = c(55, .5, 100, 60, 0.8), method = "L-BFGS-B", hessian = TRUE)
```

active regions
```{r}
theta_0 = c(60,1,350,65, 1)

results <- optim(par = theta_0, fn = ll, df = bins_data, 
      lower = c(55, .5, 100, 60, 0.8), method = "L-BFGS-B", hessian = TRUE)
```

# Discussion

## Limitations