---
title: "Chapter 6 - Results and Discussion"
author: "Joshua Ingram"
date: "5/12/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(pracma)
library(tidyverse)
library(plotly)
source("D:/main/Projects/Solar-Flare-Project/Thesis Results/Code/mu_likelihood_functionsV2.R")

GOES <- read_csv("D:/main/Datasets/Solar_REU/GOES_data/goes_clean.csv")
GOES$cycle <- as.factor(GOES$cycle)
```

# Bounded Sigmoid Model

## Total Energy

Aggregate Data
```{r}
GOES_agg <- GOES %>% filter()
values <- seq(log(min(GOES_agg$Gflrtotalenergy), 10), log(max(GOES_agg$Gflrtotalenergy), 10), length.out = 80)
width <- diff(values)[1]

df <- ggplot(data = GOES, aes(x= log(Gflrtotalenergy, 10))) + geom_histogram(center = min(values), binwidth = width)
bins_data <- ggplot_build(df)$data[[1]]
bins_data <- data.frame(y = bins_data$count, lb = bins_data$xmin, ub = bins_data$xmax, mids = bins_data$x)

theta0 = c(1.8, 2, 2, 0.001, max(bins_data$lb))

results_agg <- optim(par = theta0, fn = ll_bs, df = bins_data, H0 = 23.5, print = TRUE,
      lower = c(1.001, 0, 1, 0.0001, min(bins_data$ub)), upper = c(3, 12, 20, 10, 35),
      hessian = TRUE, control = list(fnscale = -1), method = "L-BFGS-B")
results_agg$par
cov2cor(solve(-results_agg$hessian))
sqrt(diag(solve(-results_agg$hessian)))
```

```{r}
theta_hat <- results_agg$par
mu_vals <- apply(bins_data[,c(2,3)], 1, function(x) integral(fun = mu_bs, method = "Kron", xmin = x[1], xmax = x[2], theta = theta_hat, H0 = 23.5)/ diff(x))
bins_data$mu_vals <- mu_vals

ggplot(data = GOES, aes(x= log(Gflrtotalenergy, 10))) + 
  geom_histogram(center = min(values), binwidth = width, color = "black", fill = "sienna2") + 
  geom_point(data = bins_data, aes(x = mids, y = mu_vals)) +
  theme_bw() + 
  labs(x = TeX("log_{10}(Total Energy)"), y = "Count") + 
  geom_vline(xintercept = theta_hat[5])
```

Cycle 23
```{r}
GOES_23 <- GOES %>% filter(cycle == 23)
values <- seq(log(min(GOES_23$Gflrtotalenergy), 10), log(max(GOES_23$Gflrtotalenergy), 10), length.out = 80)
width <- diff(values)[1]

df <- ggplot(data = GOES_23, aes(x= log(Gflrtotalenergy, 10))) + geom_histogram(center = min(values), binwidth = width)
bins_data <- ggplot_build(df)$data[[1]]
bins_data <- data.frame(y = bins_data$count, lb = bins_data$xmin, ub = bins_data$xmax, mids = bins_data$x)

theta0 = c(1.8, 2, 2, 0.001, max(bins_data$lb))

results_23 <- optim(par = theta0, fn = ll_bs, df = bins_data, H0 = 23.5, print = TRUE,
      lower = c(1.001, 0, 1, 0.0001, min(bins_data$ub)), upper = c(3, 12, 20, 10, 35),
      hessian = TRUE, control = list(fnscale = -1), method = "L-BFGS-B")
results_23$par
cov2cor(solve(-results_23$hessian))
sqrt(diag(solve(-results_23$hessian)))
```

```{r}
theta_hat <- results_23$par
mu_vals <- apply(bins_data[,c(2,3)], 1, function(x) integral(fun = mu_bs, method = "Kron", xmin = x[1], xmax = x[2], theta = theta_hat, H0 = 23.5)/ diff(x))
bins_data$mu_vals <- mu_vals

ggplot(data = GOES_23, aes(x= log(Gflrtotalenergy, 10))) + 
  geom_histogram(center = min(values), binwidth = width, color = "black", fill = "sienna2") + 
  geom_point(data = bins_data, aes(x = mids, y = mu_vals)) +
  theme_bw() + 
  labs(x = TeX("log_{10}(Total Energy)"), y = "Count") + 
  geom_vline(xintercept = theta_hat[5])
```

Cycle 24
```{r}
GOES_24 <- GOES %>% filter(cycle == 24)
values <- seq(log(min(GOES_24$Gflrtotalenergy), 10), log(max(GOES_24$Gflrtotalenergy), 10), length.out = 80)
width <- diff(values)[1]

df <- ggplot(data = GOES_24, aes(x= log(Gflrtotalenergy, 10))) + geom_histogram(center = min(values), binwidth = width)
bins_data <- ggplot_build(df)$data[[1]]
bins_data <- data.frame(y = bins_data$count, lb = bins_data$xmin, ub = bins_data$xmax, mids = bins_data$x)

theta0 = c(1.8, 2, 2, 0.001, max(bins_data$lb))

results_24 <- optim(par = theta0, fn = ll_bs, df = bins_data, H0 = 23.5, print = TRUE,
      lower = c(1.001, 0, 1, 0.0001, min(bins_data$ub)), upper = c(3, 12, 20, 10, 35),
      hessian = TRUE, control = list(fnscale = -1), method = "L-BFGS-B")
results_24$par
cov2cor(solve(-results_24$hessian))
sqrt(diag(solve(-results_24$hessian)))
```

```{r}
theta_hat <- results_24$par
mu_vals <- apply(bins_data[,c(2,3)], 1, function(x) integral(fun = mu_bs, method = "Kron", xmin = x[1], xmax = x[2], theta = theta_hat, H0 = 23.5)/ diff(x))
bins_data$mu_vals <- mu_vals

ggplot(data = GOES_24, aes(x= log(Gflrtotalenergy, 10))) + 
  geom_histogram(center = min(values), binwidth = width, color = "black", fill = "sienna2") + 
  geom_point(data = bins_data, aes(x = mids, y = mu_vals)) +
  theme_bw() + 
  labs(x = TeX("log_{10}(Total Energy)"), y = "Count") + 
  geom_vline(xintercept = theta_hat[5])
```

Yearly
```{r}
years <- seq(1996, 2019, 1)

results_yearly <- data.frame(year = numeric(0), convergence = numeric(0), alpha = numeric(0), kappa = numeric(0), beta = numeric(0), gamma = numeric(0), xi = numeric(0), se_alpha = numeric(0), se_kappa = numeric(0), se_beta = numeric(0), se_gamma = numeric(0), se_xi = numeric(0))
colnames(results_yearly) <- c("year", "convergence", "alpha", "kappa", "beta", "gamma", "xi", "se_alpha", "se_kappa", "se_beta", "se_gamma", "se_xi")

for (i in years){
  
  print(i)
  data <- GOES %>% filter(year == i)
  values <- seq(log(min(data$Gflrtotalenergy), 10), log(max(data$Gflrtotalenergy), 10), length.out = 80)
  width <- diff(values)[1]
  df <- ggplot(data = data, aes(x= log(Gflrtotalenergy, 10))) + geom_histogram(center = min(values), binwidth = width)
  bins_data <- ggplot_build(df)$data[[1]]
  bins_data <- data.frame(y = bins_data$count, lb = bins_data$xmin, ub = bins_data$xmax, mids = bins_data$x)

  theta0 = c(1.8, 2, 2, 1, max(bins_data$lb))

  results_y <- optim(par = theta0, fn = ll_bs, df = bins_data, H0 = 23.5, print= TRUE,
                  lower = c(1.01, 0, 1, 0.0001, min(bins_data$ub)), upper = c(3, 12, 20, 10, 35),
                  hessian = TRUE, control = list(fnscale = -1), method = "L-BFGS-B")
  convergence <- results_y$convergence
  estimates <- results_y$par
  se <- diag(solve(-results_y$hessian))
  
  output <- c(i, convergence, estimates, se)
  results_yearly <- rbind(results_yearly, output)
  colnames(results_yearly) <- c("year", "convergence", "alpha", "kappa", "beta", "gamma", "xi", "se_alpha", "se_kappa", "se_beta", "se_gamma", "se_xi")
  print(results_yearly)
  
}
```

```{r}
ggplot(data = results_yearly, aes(x= year, y = alpha)) + 
  geom_point() +
  theme_bw() + 
  labs(x = TeX("Year"), y = TeX("$\\hat{\\alpha}$")) + 
  geom_errorbar(aes(ymin = alpha - 1.96*se_alpha, ymax = alpha + 1.96*se_alpha)) +
  geom_segment(aes(x = 1996.5, xend = 2008.9, y = 2.01, yend = 2.01), color = "sienna2") +
  geom_segment(aes(x = 2008.9, xend = 2020, y = 1.88, yend = 1.88), color = "aquamarine4") +
  geom_vline(xintercept = 2008.9, alpha = 0.7, linetype = "dotted")
```


Active Regions
```{r}
GOES_AR <- GOES %>% filter(Garreg > 0)
GOES_select <- GOES_AR %>% select(Garreg, year, cycle, Gstart, Glat) %>% group_by(Garreg) %>% filter(row_number() == 1) %>% ungroup()
GOES_ar_flare_count <- GOES_AR %>% select(Garreg, year, cycle, Gstart, Glat) %>% count(Garreg)
ar_nums <- GOES_ar_flare_count %>% filter(n > 108)

results_ar <- data.frame(ar = numeric(0), convergence = numeric(0), alpha = numeric(0), kappa = numeric(0), beta = numeric(0), gamma = numeric(0), xi = numeric(0), se_alpha = numeric(0), se_kappa = numeric(0), se_beta = numeric(0), se_gamma = numeric(0), se_xi = numeric(0))
colnames(results_ar) <- c("ar", "convergence", "alpha", "kappa", "beta", "gamma", "xi", "se_alpha", "se_kappa", "se_beta", "se_gamma", "se_xi")

for (i in ar_nums$Garreg){
  
  print(i)
  data <- GOES %>% filter(Garreg == i)
  values <- seq(log(min(data$Gflrtotalenergy), 10), log(max(data$Gflrtotalenergy), 10), length.out = 50)
  width <- diff(values)[1]
  df <- ggplot(data = data, aes(x= log(Gflrtotalenergy, 10))) + geom_histogram(center = min(values), binwidth = width)
  bins_data <- ggplot_build(df)$data[[1]]
  bins_data <- data.frame(y = bins_data$count, lb = bins_data$xmin, ub = bins_data$xmax, mids = bins_data$x)

  theta0 = c(1.8, 2, 2, 1, max(bins_data$lb))
  tryCatch({
    results_r <- optim(par = theta0, fn = ll_bs, df = bins_data, H0 = 23.5, print= TRUE,
                  lower = c(1.01, 0, 1, 0.0001, min(bins_data$ub)), upper = c(3, 12, 20, 10, 35),
                  hessian = TRUE, control = list(fnscale = -1), method = "L-BFGS-B")
    convergence <- results_r$convergence
    estimates <- results_r$par
    se <- diag(solve(-results_r$hessian))
  
    output <- c(i, convergence, estimates, se)
    results_ar <- rbind(results_ar, output)
    colnames(results_ar) <- c("ar", "convergence", "alpha", "kappa", "beta", "gamma", "xi", "se_alpha", "se_kappa", "se_beta",    "se_gamma", "se_xi")
    
    
  }, finally = print(results_ar)
    
  )
  
  
}
```

```{r}
GOES %>% filter(Garreg %in% c(1294, 1361, 1424))
ggplot(data = results_ar, aes(x=ar, y = alpha)) + 
  geom_point() +
  theme_bw() + 
  labs(x = TeX("Active Region Number"), y = TeX("$\\hat{\\alpha}$")) + 
  geom_errorbar(aes(ymin = alpha - 1.96*se_alpha, ymax = alpha + 1.96*se_alpha))
```


fit to ARs where exponential is a reasonable fit

# Discussion

## Limitations