---
title: "GOES_ml_model_fitting"
author: "Joshua Ingram"
date: "5/14/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(pracma)
library(tidyverse)
library(plotly)
source("D:/main/Projects/Solar-Flare-Project/Thesis Results/Code/mu_likelihood_functionsV2.R")

GOES <- read_csv("D:/main/Datasets/Solar_REU/GOES_data/goes_clean.csv")
GOES$cycle <- as.factor(GOES$cycle)
```

# BS Model

## Total Energy

```{r}
df <- ggplot(data = GOES, aes(x= log(Gflrtotalenergy, 10))) + geom_histogram(bins = 50)
bins_data <- ggplot_build(df)$data[[1]]
bins_data <- data.frame(y = bins_data$count, lb = bins_data$xmin, ub = bins_data$xmax, mids = bins_data$x)

theta0 = c(1.8, 20, 3, 26, 27)

optim(par = theta0, fn = ll_bs, df = bins_data, H0 = 24, 
      lower = c(1.3, 18, 0.1, 25),
      upper = c(3, 21, 8, 27))
```

# 4PL Model

## Total Energy

```{r}
df <- ggplot(data = GOES, aes(x= log(Gflrtotalenergy, 10))) + geom_histogram(bins = 50)
bins_data <- ggplot_build(df)$data[[1]]
bins_data <- data.frame(y = bins_data$count, lb = bins_data$xmin, ub = bins_data$xmax, mids = bins_data$x)

theta0 = c(1.8, 20, 3, 26)

optim(par = theta0, fn = ll_4pl, df = bins_data, H0 = 24, 
      lower = c(1.1, 1, 0.1, 25))
```
